from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from django.db import transaction

from olympiad.models import (
    Center,
    Subject,
    Level,
    Question,
    Student,
    Result,
    StudentAnswer,
    MentalTask,
)


ENGLISH_TESTS = {'0-sinf': [('Banan qanday rangda bo‘ladi?', 'red', 'yellow', 'green', '', 'B'),
            ('Olma ko‘pincha qanday rangda bo‘ladi?', 'red', 'blue', 'black', '', 'A'),
            ('Barg qanday rangda bo‘ladi?', 'green', 'pink', 'white', '', 'A'),
            ('Osmon qanday rangda bo‘ladi?', 'yellow', 'blue', 'brown', '', 'B'),
            ('Sut qanday rangda bo‘ladi?', 'white', 'red', 'green', '', 'A'),
            ('Mushuk ingliz tilida nima deyiladi?', 'dog', 'cat', 'cow', '', 'B'),
            ('Kuchuk ingliz tilida nima deyiladi?', 'dog', 'fish', 'bird', '', 'A'),
            ('Sigir ingliz tilida nima deyiladi?', 'cow', 'cat', 'duck', '', 'A'),
            ('Qush ingliz tilida nima deyiladi?', 'bird', 'dog', 'horse', '', 'A'),
            ('Baliq ingliz tilida nima deyiladi?', 'fish', 'cat', 'lion', '', 'A'),
            ('Qo‘l ingliz tilida nima deyiladi?', 'hand', 'eye', 'nose', '', 'A'),
            ('Ko‘z ingliz tilida nima deyiladi?', 'ear', 'eye', 'leg', '', 'B'),
            ('Burun ingliz tilida nima deyiladi?', 'nose', 'mouth', 'hand', '', 'A'),
            ('Og‘iz ingliz tilida nima deyiladi?', 'eye', 'mouth', 'foot', '', 'B'),
            ('Quloq ingliz tilida nima deyiladi?', 'ear', 'nose', 'leg', '', 'A'),
            ('1 soni ingliz tilida nima deyiladi?', 'one', 'two', 'three', '', 'A'),
            ('2 soni ingliz tilida nima deyiladi?', 'four', 'two', 'five', '', 'B'),
            ('3 soni ingliz tilida nima deyiladi?', 'three', 'one', 'six', '', 'A'),
            ('4 soni ingliz tilida nima deyiladi?', 'two', 'four', 'seven', '', 'B'),
            ('5 soni ingliz tilida nima deyiladi?', 'five', 'three', 'one', '', 'A')],
 '1-sinf': [('What is your name?', 'I am 7', 'My name is Tom', 'Hello', 'Goodbye', 'B'),
            ('How old are you?', 'I am fine', 'I am 8 years old', 'Thank you', 'Yes, it is', 'B'),
            ('What colour is the sky?', 'Green', 'Red', 'Blue', 'Yellow', 'C'),
            ('It is an ...', 'apple', 'banana', 'cat', 'dog', 'A'),
            ('How many legs does a dog have?', 'Two', 'Four', 'Six', 'Eight', 'B'),
            ('Hello! - ... !', 'Goodbye', 'Thank you', 'Hi', 'No', 'C'),
            ('What is this? - It is ... book.', 'a', 'an', 'am', 'are', 'A'),
            ('Choose the capital letter: (Katta harfni toping)', 'a', 'b', 'M', 'e', 'C'),
            ('One, two, three, four, ...', 'six', 'five', 'seven', 'ten', 'B'),
            ('What is a tomato?', 'A fruit', 'A vegetable', 'A toy', 'An animal', 'B'),
            ('Goodbye! - ... !', 'Hello', 'Bye-bye', 'Good morning', 'Please', 'B'),
            ("My mother's sister is my ...", 'aunt', 'uncle', 'brother', 'father', 'A'),
            ('Is it a cat? - Yes, it ...', 'am', 'are', 'is', 'not', 'C'),
            ('I ... a student.', 'is', 'am', 'are', 'be', 'B'),
            ('He ... my friend.', 'is', 'am', 'are', 'not', 'A'),
            ('We ... happy.', 'am', 'is', 'are', 'be', 'C'),
            ('A banana is ...', 'red', 'blue', 'yellow', 'black', 'C'),
            ('Which one is a school object?', 'Apple', 'Pen', 'Cat', 'Car', 'B'),
            ('An elephant is ...', 'small', 'big', 'thin', 'short', 'B'),
            ('What do you say in the morning?', 'Good night', 'Good afternoon', 'Good morning', 'Goodbye', 'C')],
 '2-sinf': [('Where ... you from?', 'is', 'am', 'are', 'be', 'C'),
            ('She ... a red dress today.', 'wear', 'wears', 'is wearing', 'wearing', 'C'),
            ('They ... football every Sunday.', 'play', 'plays', 'playing', 'played', 'A'),
            ('Look! The bird ... !', 'fly', 'flies', 'is flying', 'flew', 'C'),
            ("I don't ... apples.", 'like', 'likes', 'liking', 'liked', 'A'),
            ('... she speak English?', 'Do', 'Does', 'Is', 'Are', 'B'),
            ('There ... a book on the table.', 'is', 'are', 'am', 'be', 'A'),
            ('There ... five apples in the basket.', 'is', 'are', 'am', 'was', 'B'),
            ('This is my book. That is ... book.', 'you', 'your', 'yours', 'me', 'B'),
            ('These are my pens. ... are your pens.', 'This', 'That', 'Those', 'It', 'C'),
            ('Whose bag is this? - It is ...', "Tom's", 'Tom', "Toms'", 'of Tom', 'A'),
            ('Can you ... a bicycle?', 'ride', 'drive', 'fly', 'run', 'A'),
            ('Fish can swim, but they ... fly.', 'can', 'cannot', 'must', 'should', 'B'),
            ('I ... to school yesterday.', 'go', 'goes', 'went', 'going', 'C'),
            ('Did you ... your homework?', 'do', 'does', 'did', 'done', 'A'),
            ('She ... a new book last week.', 'buy', 'buys', 'bought', 'buying', 'C'),
            ('He is ... than his brother.', 'tall', 'taller', 'tallest', 'more tall', 'B'),
            ('This is the ... car in the world.', 'fast', 'faster', 'fastest', 'most fast', 'C'),
            ("I usually get up ... 7 o'clock.", 'in', 'on', 'at', 'under', 'C'),
            ('My birthday is ... October.', 'in', 'on', 'at', 'for', 'A')],
 '3-sinf': [('Where ... you from?', 'is', 'am', 'are', 'be', 'C'),
            ('She ... a red dress today.', 'wear', 'wears', 'is wearing', 'wearing', 'C'),
            ('They ... football every Sunday.', 'play', 'plays', 'playing', 'played', 'A'),
            ('Look! The bird ... !', 'fly', 'flies', 'is flying', 'flew', 'C'),
            ("I don't ... apples.", 'like', 'likes', 'liking', 'liked', 'A'),
            ('... she speak English?', 'Do', 'Does', 'Is', 'Are', 'B'),
            ('There ... a book on the table.', 'is', 'are', 'am', 'be', 'A'),
            ('There ... five apples in the basket.', 'is', 'are', 'am', 'was', 'B'),
            ('This is my book. That is ... book.', 'you', 'your', 'yours', 'me', 'B'),
            ('These are my pens. ... are your pens.', 'This', 'That', 'Those', 'It', 'C'),
            ('Whose bag is this? - It is ...', "Tom's", 'Tom', "Toms'", 'of Tom', 'A'),
            ('Can you ... a bicycle?', 'ride', 'drive', 'fly', 'run', 'A'),
            ('Fish can swim, but they ... fly.', 'can', 'cannot', 'must', 'should', 'B'),
            ('I ... to school yesterday.', 'go', 'goes', 'went', 'going', 'C'),
            ('Did you ... your homework?', 'do', 'does', 'did', 'done', 'A'),
            ('She ... a new book last week.', 'buy', 'buys', 'bought', 'buying', 'C'),
            ('He is ... than his brother.', 'tall', 'taller', 'tallest', 'more tall', 'B'),
            ('This is the ... car in the world.', 'fast', 'faster', 'fastest', 'most fast', 'C'),
            ("I usually get up ... 7 o'clock.", 'in', 'on', 'at', 'under', 'C'),
            ('My birthday is ... October.', 'in', 'on', 'at', 'for', 'A')],
 '4-sinf': [('Look! The train ______ at the station right now, so we must hurry.', 'arrives', 'is arriving', 'has arrived', 'arrived', 'B'),
            ('While my mother ______ dinner, the lights suddenly went out.', 'cooks', 'is cooking', 'was cooking', 'cooked', 'C'),
            ('I ______ this interesting book twice this month, and I still love it.',
             'read',
             'am reading',
             'have read',
             'was reading',
             'C'),
            ('If it ______ tomorrow, we will have to cancel our outdoor picnic.', 'rains', 'will rain', 'is raining', 'rained', 'A'),
            ('She is ______ student in our class; she always gets perfect marks.',
             'intelligent',
             'more intelligent',
             'most intelligent',
             'the most intelligent',
             'D'),
            ("We ______ to London last summer, but we didn't have time to visit Big Ben.", 'go', 'went', 'have gone', 'were going', 'B'),
            ('Where ______ your brother work before he moved to Tashkent last year?', 'does', 'do', 'did', 'has done', 'C'),
            ('This smartphone is mine, but that laptop over there belongs to ______.', 'he', 'him', 'his', 'himself', 'B'),
            ('He usually ______ to school by bus, but today his father is driving him.', 'is going', 'goes', 'went', 'has gone', 'B'),
            ("They haven't finished doing their English homework ______.", 'already', 'just', 'never', 'yet', 'D'),
            ("We are planning to meet our friends ______ Sunday afternoon ______ 3 o'clock.",
             'at / on',
             'on / at',
             'in / at',
             'on / in',
             'B'),
            ("There is ______ milk left in the fridge, so we don't need to buy any today.", 'many', 'a few', 'a little', 'any', 'C'),
            ('How ______ money did you spend on these beautiful textbooks?', 'many', 'much', 'few', 'long', 'B'),
            ('The keys are not on the desk. Have you seen them ______?', 'anywhere', 'nowhere', 'somewhere', 'anything', 'A'),
            ('He walked ______ the room quietly because the baby was sleeping soundly.', 'into', 'on', 'under', 'at', 'A'),
            ("I don't have ______ questions to ask you about this new grammar lesson.", 'some', 'no', 'any', 'little', 'C'),
            ("Are you interested ______ joining our school's chess club this semester?", 'on', 'at', 'for', 'in', 'D'),
            ('There are ______ large trees in front of our main school building.', 'much', 'any', 'a few', 'a little', 'C'),
            ('She is very good ______ playing the piano and singing traditional songs.', 'in', 'at', 'with', 'for', 'B'),
            ('Please put your wet umbrella ______ the door, not inside the room.', 'behind', 'between', 'under', 'through', 'A')],
 '5-sinf': [('Look! The train ______ at the station right now, so we must hurry.', 'arrives', 'is arriving', 'has arrived', 'arrived', 'B'),
            ('While my mother ______ dinner, the lights suddenly went out.', 'cooks', 'is cooking', 'was cooking', 'cooked', 'C'),
            ('I ______ this interesting book twice this month, and I still love it.',
             'read',
             'am reading',
             'have read',
             'was reading',
             'C'),
            ('If it ______ tomorrow, we will have to cancel our outdoor picnic.', 'rains', 'will rain', 'is raining', 'rained', 'A'),
            ('She is ______ student in our class; she always gets perfect marks.',
             'intelligent',
             'more intelligent',
             'most intelligent',
             'the most intelligent',
             'D'),
            ("We ______ to London last summer, but we didn't have time to visit Big Ben.", 'go', 'went', 'have gone', 'were going', 'B'),
            ('Where ______ your brother work before he moved to Tashkent last year?', 'does', 'do', 'did', 'has done', 'C'),
            ('This smartphone is mine, but that laptop over there belongs to ______.', 'he', 'him', 'his', 'himself', 'B'),
            ('He usually ______ to school by bus, but today his father is driving him.', 'is going', 'goes', 'went', 'has gone', 'B'),
            ("They haven't finished doing their English homework ______.", 'already', 'just', 'never', 'yet', 'D'),
            ("We are planning to meet our friends ______ Sunday afternoon ______ 3 o'clock.",
             'at / on',
             'on / at',
             'in / at',
             'on / in',
             'B'),
            ("There is ______ milk left in the fridge, so we don't need to buy any today.", 'many', 'a few', 'a little', 'any', 'C'),
            ('How ______ money did you spend on these beautiful textbooks?', 'many', 'much', 'few', 'long', 'B'),
            ('The keys are not on the desk. Have you seen them ______?', 'anywhere', 'nowhere', 'somewhere', 'anything', 'A'),
            ('He walked ______ the room quietly because the baby was sleeping soundly.', 'into', 'on', 'under', 'at', 'A'),
            ("I don't have ______ questions to ask you about this new grammar lesson.", 'some', 'no', 'any', 'little', 'C'),
            ("Are you interested ______ joining our school's chess club this semester?", 'on', 'at', 'for', 'in', 'D'),
            ('There are ______ large trees in front of our main school building.', 'much', 'any', 'a few', 'a little', 'C'),
            ('She is very good ______ playing the piano and singing traditional songs.', 'in', 'at', 'with', 'for', 'B'),
            ('Please put your wet umbrella ______ the door, not inside the room.', 'behind', 'between', 'under', 'through', 'A')],
 '6-sinf': [("He ______ a new bike last week but he hasn't ridden it yet.", 'buyed', 'bought', 'has bought', 'was buying', 'B'),
            ('While we ______ a game of tennis, it suddenly started to pour.', 'played', 'were playing', 'have played', 'are playing', 'B'),
            ('I have ______ finished reading that fantasy novel you lent me.', 'yet', 'already', 'ever', 'never', 'B'),
            ('If she ______ hard enough, she will definitely pass the exam.', 'study', 'studies', 'will study', 'studied', 'B'),
            ('This task is much ______ than the previous one we did.', 'easy', 'easier', 'more easy', 'easiest', 'B'),
            ('We decided to go out ______ the weather was quite cold.', 'because', 'although', 'so', 'but', 'B'),
            ('How ______ money do you usually spend on snacks at school?', 'many', 'much', 'few', 'any', 'B'),
            ('There are only ______ apples left in the basket on the table.', 'a little', 'much', 'a few', 'any', 'C'),
            ('She is very interested ______ learning how to play classical guitar.', 'at', 'on', 'in', 'for', 'C'),
            ('The remote control is ______ the cushion and the armrest of the sofa.', 'among', 'between', 'under', 'into', 'B'),
            ("I haven't seen Sarah ______ Monday.", 'for', 'since', 'during', 'by', 'B'),
            ('They ______ dinner when the phone rang.', 'had', 'were having', 'have', 'are having', 'B'),
            ('You ______ wear a uniform at this school. It is required.', 'may', 'can', 'must', 'might', 'C'),
            ('The book ______ was on the table belongs to me.', 'who', 'which', 'where', 'when', 'B'),
            ('My brother is not old enough ______ a car.', 'drive', 'driving', 'to drive', 'drove', 'C'),
            ('She speaks English ______ than her classmates.', 'fluently', 'more fluently', 'most fluently', 'fluent', 'B'),
            ('We will call you as soon as we ______ home.', 'arrive', 'arrived', 'will arrive', 'are arriving', 'A'),
            ('The homework ______ by the students yesterday.', 'completes', 'completed', 'was completed', 'is completing', 'C'),
            ('I wish I ______ more time to practise.', 'have', 'had', 'will have', 'having', 'B'),
            ('Neither Tom nor his friends ______ ready.', 'is', 'are', 'was', 'be', 'B')],
 '7-sinf': [("He ______ a new bike last week but he hasn't ridden it yet.", 'buyed', 'bought', 'has bought', 'was buying', 'B'),
            ('While we ______ a game of tennis, it suddenly started to pour.', 'played', 'were playing', 'have played', 'are playing', 'B'),
            ('I have ______ finished reading that fantasy novel you lent me.', 'yet', 'already', 'ever', 'never', 'B'),
            ('If she ______ hard enough, she will definitely pass the exam.', 'study', 'studies', 'will study', 'studied', 'B'),
            ('This task is much ______ than the previous one we did.', 'easy', 'easier', 'more easy', 'easiest', 'B'),
            ('We decided to go out ______ the weather was quite cold.', 'because', 'although', 'so', 'but', 'B'),
            ('How ______ money do you usually spend on snacks at school?', 'many', 'much', 'few', 'any', 'B'),
            ('There are only ______ apples left in the basket on the table.', 'a little', 'much', 'a few', 'any', 'C'),
            ('She is very interested ______ learning how to play classical guitar.', 'at', 'on', 'in', 'for', 'C'),
            ('The remote control is ______ the cushion and the armrest of the sofa.', 'among', 'between', 'under', 'into', 'B'),
            ("I haven't seen Sarah ______ Monday.", 'for', 'since', 'during', 'by', 'B'),
            ('They ______ dinner when the phone rang.', 'had', 'were having', 'have', 'are having', 'B'),
            ('You ______ wear a uniform at this school. It is required.', 'may', 'can', 'must', 'might', 'C'),
            ('The book ______ was on the table belongs to me.', 'who', 'which', 'where', 'when', 'B'),
            ('My brother is not old enough ______ a car.', 'drive', 'driving', 'to drive', 'drove', 'C'),
            ('She speaks English ______ than her classmates.', 'fluently', 'more fluently', 'most fluently', 'fluent', 'B'),
            ('We will call you as soon as we ______ home.', 'arrive', 'arrived', 'will arrive', 'are arriving', 'A'),
            ('The homework ______ by the students yesterday.', 'completes', 'completed', 'was completed', 'is completing', 'C'),
            ('I wish I ______ more time to practise.', 'have', 'had', 'will have', 'having', 'B'),
            ('Neither Tom nor his friends ______ ready.', 'is', 'are', 'was', 'be', 'B')],
 'Qiyin': [("He ______ a new bike last week but he hasn't ridden it yet.", 'buyed', 'bought', 'has bought', 'was buying', 'B'),
           ('While we ______ a game of tennis, it suddenly started to pour.', 'played', 'were playing', 'have played', 'are playing', 'B'),
           ('I have ______ finished reading that fantasy novel you lent me.', 'yet', 'already', 'ever', 'never', 'B'),
           ('If she ______ hard enough, she will definitely pass the exam.', 'study', 'studies', 'will study', 'studied', 'B'),
           ('This task is much ______ than the previous one we did.', 'easy', 'easier', 'more easy', 'easiest', 'B'),
           ('We decided to go out ______ the weather was quite cold.', 'because', 'although', 'so', 'but', 'B'),
           ('How ______ money do you usually spend on snacks at school?', 'many', 'much', 'few', 'any', 'B'),
           ('There are only ______ apples left in the basket on the table.', 'a little', 'much', 'a few', 'any', 'C'),
           ('She is very interested ______ learning how to play classical guitar.', 'at', 'on', 'in', 'for', 'C'),
           ('The remote control is ______ the cushion and the armrest of the sofa.', 'among', 'between', 'under', 'into', 'B'),
           ("I haven't seen Sarah ______ Monday.", 'for', 'since', 'during', 'by', 'B'),
           ('They ______ dinner when the phone rang.', 'had', 'were having', 'have', 'are having', 'B'),
           ('You ______ wear a uniform at this school. It is required.', 'may', 'can', 'must', 'might', 'C'),
           ('The book ______ was on the table belongs to me.', 'who', 'which', 'where', 'when', 'B'),
           ('My brother is not old enough ______ a car.', 'drive', 'driving', 'to drive', 'drove', 'C'),
           ('She speaks English ______ than her classmates.', 'fluently', 'more fluently', 'most fluently', 'fluent', 'B'),
           ('We will call you as soon as we ______ home.', 'arrive', 'arrived', 'will arrive', 'are arriving', 'A'),
           ('The homework ______ by the students yesterday.', 'completes', 'completed', 'was completed', 'is completing', 'C'),
           ('I wish I ______ more time to practise.', 'have', 'had', 'will have', 'having', 'B'),
           ('Neither Tom nor his friends ______ ready.', 'is', 'are', 'was', 'be', 'B')]}

RUS_TESTS = {
    'boxcha': [
        ('Banan qanday rangda bo‘ladi?', 'красный', 'жёлтый', 'зелёный', '', 'B'),
        ('Osmon qanday rangda bo‘ladi?', 'синий', 'чёрный', 'красный', '', 'A'),
        ('Barg qanday rangda bo‘ladi?', 'белый', 'зелёный', 'жёлтый', '', 'B'),
        ('Qor qanday rangda bo‘ladi?', 'белый', 'красный', 'синий', '', 'A'),
        ('Pomidor qanday rangda bo‘ladi?', 'зелёный', 'чёрный', 'красный', '', 'C'),
        ('Mushuk rus tilida nima deyiladi?', 'кошка', 'собака', 'корова', '', 'A'),
        ('Kuchuk rus tilida nima deyiladi?', 'рыба', 'собака', 'птица', '', 'B'),
        ('Sigir rus tilida nima deyiladi?', 'корова', 'кошка', 'заяц', '', 'A'),
        ('Qush rus tilida nima deyiladi?', 'птица', 'собака', 'лошадь', '', 'A'),
        ('Baliq rus tilida nima deyiladi?', 'рыба', 'кот', 'мышь', '', 'A'),
        ('Qo‘l rus tilida nima deyiladi?', 'рука', 'нога', 'глаз', '', 'A'),
        ('Ko‘z rus tilida nima deyiladi?', 'нос', 'глаз', 'рот', '', 'B'),
        ('Burun rus tilida nima deyiladi?', 'ухо', 'рука', 'нос', '', 'C'),
        ('Og‘iz rus tilida nima deyiladi?', 'рот', 'глаз', 'нога', '', 'A'),
        ('Quloq rus tilida nima deyiladi?', 'нос', 'ухо', 'рука', '', 'B'),
        ('1 soni rus tilida nima deyiladi?', 'один', 'два', 'три', '', 'A'),
        ('2 soni rus tilida nima deyiladi?', 'четыре', 'два', 'пять', '', 'B'),
        ('3 soni rus tilida nima deyiladi?', 'три', 'один', 'шесть', '', 'A'),
        ('“Salom” rus tilida nima deyiladi?', 'привет', 'пока', 'спасибо', '', 'A'),
        ('“Rahmat” rus tilida nima deyiladi?', 'да', 'нет', 'спасибо', '', 'C'),
    ],
    '2-sinf': [
        ('Когда я пришёл, мама уже ___ ужин.', 'готовит', 'готовила', 'приготовила', 'готовить', 'C'),
        ('Если будет дождь, мы ___ дома.', 'останемся', 'оставались', 'остаёмся', 'остаться', 'A'),
        ('Я знаю девушку, ___ живёт рядом.', 'который', 'которая', 'которое', 'которые', 'B'),
        ('Мы часто ___ в библиотеку после уроков.', 'ходим', 'ходили', 'пойдём', 'ходить', 'A'),
        ('Вчера они долго ___ домашнее задание.', 'делают', 'делали', 'сделать', 'сделают', 'B'),
        ('Она сказала, что ___ завтра.', 'придёт', 'приходит', 'пришла', 'приходить', 'A'),
        ('Я интересуюсь ___', 'спорт', 'спорта', 'спортом', 'спорту', 'C'),
        ('У меня нет ___ времени.', 'свободное', 'свободного', 'свободный', 'свободному', 'B'),
        ('Мы поехали в город ___ автобусе.', 'на', 'в', 'под', 'с', 'A'),
        ('Этот фильм намного ___ того фильма.', 'интереснее', 'интересный', 'интересно', 'интересен', 'A'),
        ('Я начал ___ русский язык два года назад.', 'изучаю', 'изучать', 'изучал', 'изучит', 'B'),
        ('Если бы у меня было время, я ___ спортом.', 'занимался бы', 'занимаюсь', 'занялся', 'заниматься', 'A'),
        ('Учитель попросил нас ___ упражнение.', 'выполнить', 'выполняем', 'выполняли', 'выполняет', 'A'),
        ('Мы гордимся ___ школой.', 'наша', 'нашей', 'нашу', 'нашейю', 'B'),
        ('Он умеет хорошо ___ на гитаре.', 'играет', 'играть', 'играл', 'играющий', 'B'),
        ('Я не понимаю, о чём они ___', 'говорят', 'говорим', 'говоришь', 'говорить', 'A'),
        ('Когда я был маленьким, я часто ___ у бабушки.', 'отдыхал', 'отдыхаю', 'отдыхает', 'отдыхать', 'A'),
        ('Мы ждём друзей уже два ___', 'часа', 'час', 'часов', 'часу', 'A'),
        ('Она самая ___ ученица в классе.', 'умный', 'умная', 'умнее', 'умных', 'B'),
        ('Я хочу, чтобы ты ___ вовремя.', 'пришёл', 'приходишь', 'приходит', 'прийти', 'A'),
    ],
    '3-sinf': [
        ('После школы дети пошли ___ футбол.', 'играть', 'играют', 'играл', 'играет', 'A'),
        ('Он рассказал мне интересную ___', 'историю', 'история', 'историей', 'истории', 'A'),
        ('Мы познакомились ___ конференции.', 'на', 'в', 'под', 'около', 'A'),
        ('Завтра будет намного ___', 'тепло', 'теплее', 'тёплый', 'теплота', 'B'),
        ('Я давно не видел своих ___', 'друзья', 'друзьям', 'друзей', 'друзьями', 'C'),
        ('Она всегда помогает ___ маме.', 'свою', 'своей', 'своего', 'своим', 'B'),
        ('Мы решили ___ в музее.', 'встретиться', 'встречаемся', 'встретились', 'встречаться', 'A'),
        ('Ученики внимательно слушали ___', 'учитель', 'учителя', 'учителю', 'учителем', 'B'),
        ('Мне нравится музыка, ___ слушает мой брат.', 'который', 'которую', 'которое', 'которых', 'B'),
        ('Я думаю, что экзамен будет ___', 'лёгкий', 'лёгким', 'легко', 'легче', 'B'),
        ('В комнате было так темно, что ничего не ___', 'видно', 'виден', 'видна', 'видны', 'A'),
        ('Мы приехали домой поздно, потому что долго ___ автобус.', 'ждали', 'ждём', 'ждать', 'подождали', 'A'),
        ('Если ты не понял правило, я могу ещё раз ___', 'объяснить', 'объясняю', 'объяснил', 'объясняет', 'A'),
        ('Она занимается танцами с ___ детства.', 'ранний', 'раннего', 'ранним', 'раннее', 'B'),
        ('Мы любим путешествовать ___ стране.', 'по', 'на', 'в', 'у', 'A'),
        ('Этот студент учится лучше, ___ остальные.', 'как', 'чем', 'что', 'потому', 'B'),
        ('Я рад, что вы ___ на встречу.', 'пришли', 'пришёл', 'придёт', 'приходить', 'A'),
        ('Он всегда мечтал ___ врачом.', 'стать', 'становится', 'стал', 'становиться', 'A'),
        ('Мне нужно купить подарок ___ сестры.', 'для', 'от', 'у', 'к', 'A'),
        ('Когда закончится урок, мы ___ домой.', 'пойдём', 'идём', 'ходили', 'идти', 'A'),
    ],
    '4-sinf': [
        ('После школы дети пошли ___ футбол.', 'играть', 'играют', 'играл', 'играет', 'A'),
        ('Он рассказал мне интересную ___', 'историю', 'история', 'историей', 'истории', 'A'),
        ('Мы познакомились ___ конференции.', 'на', 'в', 'под', 'около', 'A'),
        ('Завтра будет намного ___', 'тепло', 'теплее', 'тёплый', 'теплота', 'B'),
        ('Я давно не видел своих ___', 'друзья', 'друзьям', 'друзей', 'друзьями', 'C'),
        ('Она всегда помогает ___ маме.', 'свою', 'своей', 'своего', 'своим', 'B'),
        ('Мы решили ___ в музее.', 'встретиться', 'встречаемся', 'встретились', 'встречаться', 'A'),
        ('Ученики внимательно слушали ___', 'учитель', 'учителя', 'учителю', 'учителем', 'B'),
        ('Мне нравится музыка, ___ слушает мой брат.', 'который', 'которую', 'которое', 'которых', 'B'),
        ('Я думаю, что экзамен будет ___', 'лёгкий', 'лёгким', 'легко', 'легче', 'B'),
        ('В комнате было так темно, что ничего не ___', 'видно', 'виден', 'видна', 'видны', 'A'),
        ('Мы приехали домой поздно, потому что долго ___ автобус.', 'ждали', 'ждём', 'ждать', 'подождали', 'A'),
        ('Если ты не понял правило, я могу ещё раз ___', 'объяснить', 'объясняю', 'объяснил', 'объясняет', 'A'),
        ('Она занимается танцами с ___ детства.', 'ранний', 'раннего', 'ранним', 'раннее', 'B'),
        ('Мы любим путешествовать ___ стране.', 'по', 'на', 'в', 'у', 'A'),
        ('Этот студент учится лучше, ___ остальные.', 'как', 'чем', 'что', 'потому', 'B'),
        ('Я рад, что вы ___ на встречу.', 'пришли', 'пришёл', 'придёт', 'приходить', 'A'),
        ('Он всегда мечтал ___ врачом.', 'стать', 'становится', 'стал', 'становиться', 'A'),
        ('Мне нужно купить подарок ___ сестры.', 'для', 'от', 'у', 'к', 'A'),
        ('Когда закончится урок, мы ___ домой.', 'пойдём', 'идём', 'ходили', 'идти', 'A'),
    ],
    '5-sinf': [
        ('Найди значение выражения / Ifodani qiymatini toping: (237 + 486) – (512 – 163).', '374', '274', '574', '484', 'A'),
        ('У Мадины было 120 яблок. Она продала 1/3 всех яблок, а потом ещё 20. Сколько яблок у неё осталось? / Madinada 120 ta olma bor edi. U olmalarning 1/3 qismini, keyin yana 20 tasini sotdi. Qancha olma qoldi?', '80', '40', '60', '50', 'C'),
        ('В автобусе ехали 38 человек. На остановке вышли 12 человек и зашли ещё 9. Сколько человек стало в автобусе? / Avtobusda 38 kishi bor edi. Bekatda 12 kishi chiqib, yana 9 kishi kirdi. Avtobusda qancha odam qoldi?', '35', '37', '36', '34', 'A'),
        ('Анвар задумал число. Если его умножить на 7, получится 91. Какое число задумал Анвар? / Anvar son o‘yladi. Agar u 7 ga ko‘paytirilsa, 91 bo‘ladi. Anvar qanday sonni o‘ylagan?', '21', '7', '14', '13', 'D'),
        ('Найди периметр квадрата со стороной 17 см. / Tomoni 17 sm bo‘lgan kvadratning perimetrini toping.', '64 см', '72 см', '68 см', '34 см', 'C'),
        ('Сколько всего прямоугольников изображено на рисунке (сетка 2×3)? / Rasmda jami qancha to‘rtburchak ko‘rsatilgan (2×3 panjara)?', '12', '20', '15', '18', 'D'),
        ('У круга радиус 6 см. Найди длину окружности. / Doira radiusi 6 sm. Aylana uzunligini toping.', '≈ 31,4 см', '≈ 25,1 см', '≈ 37,7 см', '≈ 43,9 см', 'C'),
        ('У прямоугольника одна сторона 8 см, другая в 3 раза длиннее. Найди площадь прямоугольника. / To‘rtburchakning bir tomoni 8 sm, ikkinchisi 3 baravar uzun. Maydonini toping.', '128 см²', '192 см²', '64 см²', '256 см²', 'B'),
        ('На картинке изображён треугольник. Одна сторона 10 см, вторая 8 см, угол между ними прямой. Найди площадь треугольника. / Bir tomoni 10 sm, ikkinchisi 8 sm, orasidagi burchak to‘g‘ri. Uchburchak maydonini toping.', '50 см²', '40 см²', '60 см²', '80 см²', 'B'),
        ('Доска длиной 2 м была распилена на части по 25 см. Сколько частей получилось? / Uzunligi 2 m bo‘lgan taxta 25 sm bo‘laklarga bo‘lindi. Nechta qism bo‘ldi?', '8', '7', '6', '9', 'A'),
        ('В комнате горят 3 лампочки. Алишер щёлкнул выключателем 5 раз. Может ли все лампочки погаснуть? / Xonada 3 ta lampochka yongan. Alisher kalitni 5 marta bosdi. Barcha lampalar o‘chishi mumkinmi?', 'Нет / Yo‘q', 'Да, иногда / Ha, ba’zida', 'Зависит от числа щелчков / Bosishlar soniga qarab', 'Да, всегда / Ha, har doim', 'D'),
        ('У двух братьев вместе 26 яблок. У одного их на 8 больше, чем у другого. Сколько яблок у каждого? / Ikki aka-ukada jami 26 ta olma bor. Birida boshqasidan 8 ta ko‘p. Har birida nechta olma bor?', '18 и 8', '17 и 9', '19 и 7', '20 и 6', 'B'),
        ('Папа старше сына на 30 лет. Через 10 лет возраст отца будет в 2 раза больше возраста сына. Сколько лет сыну сейчас? / Ota o‘g‘lidan 30 yosh katta. 10 yildan keyin ota o‘g‘lidan 2 marta katta bo‘ladi. Hozir o‘g‘li necha yoshda?', '15 лет', '25 лет', '10 лет', '20 лет', 'D'),
        ('Часы показывают 3 часа 15 минут. Какой угол между часовой и минутной стрелкой? / Soat 3:15 ni ko‘rsatmoqda. Soat va daqiqa millari orasidagi burchak qanday?', '52,5°', '45°', '75°', '60°', 'A'),
        ('Алишер записал подряд все числа от 1 до 50. Сколько раз он написал цифру «3»? / Alisher 1 dan 50 gacha bo‘lgan sonlarni yozdi. U “3” raqamini necha marta yozgan?', '15', '10', '20', '12', 'A'),
        ('Найди число «?»: 12 18 24 / 14 20 ?.', '24', '26', '22', '28', 'B'),
        ('Три девочки: Асила, Мадина, Омина. Асила выше Мадины. Омина ниже Мадины. Кто самая высокая? / Asila Madinadan balandroq, Omina Madinadan pastroq. Eng baland kim?', 'Невозможно определить / Aniqlab bo‘lmaydi', 'Омина', 'Мадина', 'Асила', 'D'),
        ('У Камолы 5 красных, 7 синих и 3 зелёных карандаша. Сколько карандашей надо взять, чтобы быть уверенной, что два будут одного цвета? / Kamolada 5 ta qizil, 7 ta ko‘k va 3 ta yashil qalam bor. Ikkitasi bir xil rangda bo‘lishiga ishonch hosil qilish uchun nechta qalam olish kerak?', '5', '3', '6', '4', 'D'),
        ('В магазин привезли 48 кг яблок и 36 кг груш. Всё разложили в одинаковые ящики. Какой максимальный вес может быть у одного ящика? / 48 kg olma va 36 kg nok bir xil qutilarga joylandi. Bitta qutining maksimal og‘irligi qancha?', '10 кг', '8 кг', '12 кг', '6 кг', 'C'),
        ('Санжар решил: x + 25 = 78. x = ? / Sanjar yechdi: x + 25 = 78. x = ?', '53', '54', '55', '52', 'A'),
    ],
    '6-sinf': [
        ('Если бы у меня было больше времени, я ___ спортом каждый день.', 'занимаюсь', 'занимался бы', 'занимался', 'заниматься', 'B'),
        ('Учитель сказал, что контрольная работа ___ завтра.', 'была', 'бывают', 'будеть', 'будет', 'D'),
        ('Мы не пошли гулять, потому что на улице ___ дождь.', 'шёл', 'идёт', 'идти', 'пойдёт', 'A'),
        ('Мама попросила меня ___ в магазин за хлебом.', 'ходил', 'хожу', 'сходить', 'ходить', 'C'),
        ('Я знаю мальчика, ___ живёт рядом с нами.', 'которую', 'который', 'которое', 'которых', 'B'),
        ('Этот фильм оказался намного ___, чем я ожидал.', 'интереснее', 'интересный', 'интересно', 'интересен', 'A'),
        ('Если ты не будешь читать книги, твой словарный запас не ___', 'увеличивался', 'увеличивается', 'увеличивать', 'увеличится', 'D'),
        ('Когда мы пришли на стадион, матч уже ___', 'начинался', 'начался', 'начинается', 'начнётся', 'B'),
        ('Ученики внимательно слушали учителя, чтобы всё правильно ___', 'понимают', 'понимали', 'понять', 'понял', 'C'),
        ('Я очень рад, что ты успешно ___ экзамен.', 'сдал', 'сдашь', 'сдаёшь', 'сдавать', 'A'),
        ('Несмотря ___ плохую погоду, соревнование состоялось.', 'в', 'под', 'с', 'на', 'D'),
        ('Она всегда старается выполнять задания ___', 'аккуратный', 'аккуратно', 'аккуратнее', 'аккуратность', 'B'),
        ('Мы решили остаться дома, так как очень ___', 'устал', 'устала', 'устали', 'устать', 'C'),
        ('Мне нравится музыка, ___ слушает мой брат.', 'которую', 'который', 'которое', 'которых', 'A'),
        ('Учитель объяснил правило так хорошо, что все ученики быстро его ___', 'понимают', 'понять', 'поймут', 'поняли', 'D'),
        ('Если завтра будет хорошая погода, мы ___ на экскурсию.', 'поехали', 'едем', 'поедем', 'ехать', 'C'),
        ('Родители хотят, чтобы их дети хорошо ___', 'учились', 'учатся', 'учиться', 'учат', 'A'),
        ('Она спросила меня, ___ ли я домашнее задание.', 'делаю', 'сделал', 'делать', 'сделаю', 'B'),
        ('Мы познакомились с человеком, ___ работает врачом.', 'которую', 'которое', 'которых', 'который', 'D'),
        ('После уроков дети пошли ___ в футбол.', 'играют', 'играл', 'играть', 'играет', 'C'),
    ],
    '7-sinf': [
        ('Если бы у меня было больше времени, я ___ спортом каждый день.', 'занимаюсь', 'занимался бы', 'занимался', 'заниматься', 'B'),
        ('Учитель сказал, что контрольная работа ___ завтра.', 'была', 'бывают', 'будеть', 'будет', 'D'),
        ('Мы не пошли гулять, потому что на улице ___ дождь.', 'шёл', 'идёт', 'идти', 'пойдёт', 'A'),
        ('Мама попросила меня ___ в магазин за хлебом.', 'ходил', 'хожу', 'сходить', 'ходить', 'C'),
        ('Я знаю мальчика, ___ живёт рядом с нами.', 'которую', 'который', 'которое', 'которых', 'B'),
        ('Этот фильм оказался намного ___, чем я ожидал.', 'интереснее', 'интересный', 'интересно', 'интересен', 'A'),
        ('Если ты не будешь читать книги, твой словарный запас не ___', 'увеличивался', 'увеличивается', 'увеличивать', 'увеличится', 'D'),
        ('Когда мы пришли на стадион, матч уже ___', 'начинался', 'начался', 'начинается', 'начнётся', 'B'),
        ('Ученики внимательно слушали учителя, чтобы всё правильно ___', 'понимают', 'понимали', 'понять', 'понял', 'C'),
        ('Я очень рад, что ты успешно ___ экзамен.', 'сдал', 'сдашь', 'сдаёшь', 'сдавать', 'A'),
        ('Несмотря ___ плохую погоду, соревнование состоялось.', 'в', 'под', 'с', 'на', 'D'),
        ('Она всегда старается выполнять задания ___', 'аккуратный', 'аккуратно', 'аккуратнее', 'аккуратность', 'B'),
        ('Мы решили остаться дома, так как очень ___', 'устал', 'устала', 'устали', 'устать', 'C'),
        ('Мне нравится музыка, ___ слушает мой брат.', 'которую', 'который', 'которое', 'которых', 'A'),
        ('Учитель объяснил правило так хорошо, что все ученики быстро его ___', 'понимают', 'понять', 'поймут', 'поняли', 'D'),
        ('Если завтра будет хорошая погода, мы ___ на экскурсию.', 'поехали', 'едем', 'поедем', 'ехать', 'C'),
        ('Родители хотят, чтобы их дети хорошо ___', 'учились', 'учатся', 'учиться', 'учат', 'A'),
        ('Она спросила меня, ___ ли я домашнее задание.', 'делаю', 'сделал', 'делать', 'сделаю', 'B'),
        ('Мы познакомились с человеком, ___ работает врачом.', 'которую', 'которое', 'которых', 'который', 'D'),
        ('После уроков дети пошли ___ в футбол.', 'играют', 'играл', 'играть', 'играет', 'C'),
    ],
    '8-sinf': [
        ('Вопрос к выделенной части предложения «Журналист написал в своей статье о том, что саксаул занесен в Красную книгу»:', 'Кто написал о том, что саксаул занесен в Красную книгу?', 'О чем написал журналист в своей статье?', 'Куда занесен саксаул?', 'Где журналист написал о том, что саксаул занесен в Красную книгу?', 'B'),
        ('Тире должно стоять в предложении:', 'Дыня прекрасное средство от депрессии и плохого настроения.', 'В Узбекистане выращивается более 160 сортов дынь.', 'В Бухаре растет тутовник которому уже 600 лет.', 'Хлопок называют белым золотом Узбекистана.', 'A'),
        ('Учитель попросил, … ученики принесли в класс несколько стульев.', 'что', 'потому что', 'для', 'чтобы', 'D'),
        ('Хлопкоробы бережно ухаживают … каждым ростком хлопка, … получить богатый урожай.', 'для, что', 'за, чтобы', 'благодаря, что', 'о, потому что', 'B'),
        ('Правильный ответ на вопрос: «Подруга спросила меня, видела ли я северного оленя»:', 'Нет, не северного оленя.', 'Да, северного оленя.', 'Нет, не видела.', 'Да, я.', 'C'),
        ('В Узбекистане, … в Белоруссии, любят гнездиться аисты.', 'чем', 'как будто', 'как', 'как и', 'D'),
        ('Вместо точек в предложении «Аисты любят … свои гнезда на крышах домов» НЕЛЬЗЯ использовать слово…', 'строить', 'вить', 'оберегать', 'делать', 'C'),
        ('Спорт … укреплению физического и психического здоровья.', 'способствует', 'вредит', 'делает', 'влияет', 'A'),
        ('Укрепление … детей — важная задача школы.', 'здоровье', 'здоровья', 'здоровьем', 'здоровью', 'B'),
        ('Некоторые виды растений и животных … … вмешательства человека в природу.', 'появились благодаря', 'сохранились потому что', 'исчезли из-за', 'погибли в связи с', 'C'),
        ('Найдите побудительное предложение ?', 'Человек должен быть заботливым.', 'Что объединяет людей?', 'Переходите улицу только в положенном месте', 'В какой стране ты живёшь?', 'C'),
        ('Продолжите пословицу: Не привыкай к безделью,….', 'а работай', 'учись трудится', 'учись уму', 'учись рукоделью', 'D'),
        ('Где находится медресе Кукельдаш?', 'В Ташкенте', 'В Бухаре', 'В Хиве', 'В Самарканде', 'A'),
        ('Сколько лет было Улугбеку, когда он стал править Самаркандом?', '18 лет', '15 лет', '13 лет', '19 лет', 'B'),
        ('Второстепенный член предложения, который отвечает на вопросы косвенных падежей – это ….', 'Определение', 'обстоятельство', 'Дополнение', 'сказуемое', 'C'),
        ('Группа слов, которые объединены общим законченным смыслом и интонацией -это', 'Синтаксис', 'Предложение', 'Пунктуация', 'Словосочетание', 'B'),
        ('Родился в семье помещика. С детских лет он видел тяжёлую жизнь простых людей, рос по среди крестьянских детей, любил народ, родную землю её природу. Кто это?', 'А. Фет;', 'Ф. Тютчев;', 'А.С. Пушкин;', 'Н. Некрасов;', 'D'),
        ('Где были написаны Пушкином «Повести Белкина»?', 'На Кавказе', 'В Михайловском', 'В селе Болдино', 'В Москве', 'C'),
        ('Какие цветы взял Петрусь у девочки ? (“Слепой музыкант”)', 'фиалка и мак', 'лютик и фиалка', 'ромашка и тюльпан', 'василёк и мак', 'B'),
        ('Для сообщения фактов, явлений, действий употребляются …', 'повествовательные предложения', 'вопросительные предложения', 'восклицательные предложения', 'побудительные предложения', 'A'),
    ],
    '9-sinf': [
        ('Вопрос к выделенной части предложения: «Журналист написал в своей статье о том, что саксаул занесен в Красную книгу».', 'Кто написал о том, что саксаул занесен в Красную книгу?', 'О чем написал журналист в своей статье?', 'Куда занесен саксаул?', 'Где журналист написал о том, что саксаул занесен в Красную книгу?', 'B'),
        ('Тире должно стоять в предложении:', 'Дыня — прекрасное средство от депрессии и плохого настроения.', 'В Узбекистане выращивается более 160 сортов дынь.', 'В Бухаре растет тутовник которому уже 600 лет.', 'Хлопок называют белым золотом Узбекистана.', 'A'),
        ('Учитель попросил, … ученики принесли в класс несколько стульев.', 'что', 'потому что', 'для', 'чтобы', 'D'),
        ('Хлопкоробы бережно ухаживают … каждым ростком хлопка, … получить богатый урожай.', 'для, что', 'за, чтобы', 'благодаря, что', 'о, потому что', 'B'),
        ('Правильный ответ на вопрос: «Подруга спросила меня, видела ли я северного оленя».', 'Нет, не северного оленя.', 'Да, северного оленя.', 'Нет, не видела.', 'Да, я.', 'C'),
        ('В Узбекистане, … в Белоруссии, любят гнездиться аисты.', 'чем', 'как будто', 'как', 'как и', 'D'),
        ('Вместо точек в предложении «Аисты любят … свои гнезда на крышах домов» НЕЛЬЗЯ использовать слово…', 'строить', 'вить', 'оберегать', 'делать', 'C'),
        ('Спорт … укреплению физического и психического здоровья.', 'способствует', 'вредит', 'делает', 'влияет', 'A'),
        ('Укрепление … детей — важная задача школы.', 'здоровье', 'здоровья', 'здоровьем', 'здоровью', 'B'),
        ('Некоторые виды растений и животных … … вмешательства человека в природу.', 'появились благодаря', 'сохранились потому что', 'исчезли из-за', 'погибли в связи с', 'C'),
        ('В январе 2020 года для биоразнообразия в Узбекистан были привезены … олени и … лани.', 'благородные, европейские', 'благородный, европейская', 'благородных, европейских', 'благородным, европейским', 'A'),
        ('Благородный олень — это изящное и красивое животное с … осанкой.', 'гордой', 'гордая', 'гордую', 'гордым', 'A'),
        ('... часто называют белым золотом.', 'хлопок', 'саксаул', 'тутовник', 'олень', 'A'),
        ('Какое дерево выше: тутовник или саксаул?', 'тутовник', 'саксаул', 'оба одинаковые', 'невозможно определить', 'A'),
        ('Какое дерево может расти в пустыне?', 'саксаул', 'тутовник', 'яблоня', 'берёза', 'A'),
        ('Саксаул занесен ___ Красную книгу.', 'в', 'на', 'к', 'под', 'A'),
        ('В Бухаре растет тутовник, ___ уже 600 лет.', 'которому', 'который', 'которого', 'которым', 'A'),
        ('Спорт способствует ___ здоровья.', 'укреплению', 'укрепление', 'укреплением', 'укреплять', 'A'),
        ('Аисты любят гнездиться ___ крышах домов.', 'на', 'в', 'под', 'с', 'A'),
        ('Хлопок называют ___ золотом Узбекистана.', 'белым', 'белого', 'белое', 'белая', 'A'),
    ],

    '10-sinf': [
        ('Символ Олимпийских игр был разработан в ... году.', '1912', '1920', '1922', '1936', 'A'),
        ('Впервые Олимпийские кольца появились на Олимпиаде в ...', 'Америке', 'Бельгии', 'России', 'Греции', 'B'),
        ('Олимпийские кольца символизируют ...', 'спорт', 'союз континентов', 'соревнование', 'победу', 'B'),
        ('Выберите «лишнее слово»:', 'критиковать', 'клеймить', 'характеризовать', 'осуждать', 'C'),
        ('Рядом с нами построили ... дом.', 'житейский', 'жизненный', 'жилой', 'живой', 'C'),
        ('Он был ... работником.', 'исполнительным', 'исполнительским', 'исполненным', 'исполняемым', 'A'),
        ('Мы внимательно слушали Алексея. Он был ... рассказчиком.', 'искусственным', 'искусным', 'искусствоведческим', 'искусственным образом', 'B'),
        ('Выберите ряд многозначных слов:', 'компьютер, чемодан', 'дискуссия, переутомление', 'молния, линия', 'карандаш, парта', 'C'),
        ('Выберите строку с синонимами:', 'завышать, занижать', 'терять, находить', 'праздновать, отмечать', 'молчать, говорить', 'C'),
        ('Выберите фразеологическую единицу — синоним к словосочетанию «хорошо работать».', 'вставлять палки в колёса', 'засучив рукава', 'как свои пять пальцев', 'бить баклуши', 'B'),
        ('Создателем первой электрической лампочки считается ...', 'Томас Эдисон', 'Александр Белл', 'Борис Грабовский', 'Исаак Ньютон', 'A'),
        ('Бостонский изобретатель Александр Грейам Белл автор ...', 'телефона', 'телевизора', 'электрической лампочки', 'радио', 'A'),
        ('В Ташкенте Борис Грабовский создал первый в мире ...', 'телевизор', 'телефон', 'компьютер', 'самолёт', 'A'),
        ('Переведите слово «изобретатель» на узбекский язык.', 'ixtirochi', 'olim', 'muhandis', 'yozuvchi', 'A'),
        ('Кто сказал: «Наука — сила, она раскрывает отношения вещей, их законы и взаимодействия»?', 'А. М. Горький', 'А. С. Пушкин', 'Л. Н. Толстой', 'И. С. Тургенев', 'A'),
        ('Как называется человек, который создаёт новые устройства и идеи?', 'изобретатель', 'спортсмен', 'переводчик', 'путешественник', 'A'),
        ('Какое слово ближе по значению к слову «изобретение»?', 'открытие', 'ошибка', 'спор', 'память', 'A'),
        ('Олимпийский символ состоит из пяти ...', 'колец', 'звёзд', 'кругов и линий', 'флагов', 'A'),
        ('Какое словосочетание составлено правильно?', 'жилой дом', 'житейский дом', 'искусственный рассказчик', 'исполнительский работник', 'A'),
        ('Выберите правильное продолжение: Спорт способствует ...', 'укреплению здоровья', 'укрепление здоровья', 'укреплять здоровья', 'укреплением здоровье', 'A'),
    ],
}


MATH_TESTS = {'0-sinf': [
            ('2 + 3 = ?', '4', '5', '6', '7', 'B'),
            ('6 - 2 = ?', '2', '3', '4', '5', 'C'),
            ('4 + 4 = ?', '6', '7', '8', '9', 'C'),
            ('10 - 5 = ?', '4', '5', '6', '7', 'B'),
            ('1 + 6 = ?', '5', '6', '7', '8', 'C'),
            ('9 - 3 = ?', '5', '6', '7', '8', 'B'),
            ('5 + 2 = ?', '6', '7', '8', '9', 'B'),
            ('8 - 4 = ?', '3', '4', '5', '6', 'B'),
            ('3 + 5 = ?', '7', '8', '9', '10', 'B'),
            ('7 - 1 = ?', '5', '6', '7', '8', 'B'),
            ('Qaysi son 5 dan katta?', '3', '4', '6', '5', 'C'),
            ('Qaysi son 9 dan kichik?', '10', '11', '8', '12', 'C'),
            ('1, 2, 3, 4, __ . Keyingi son qaysi?', '5', '6', '7', '8', 'A'),
            ('10, 9, 8, 7, __ . Keyingi son qaysi?', '5', '6', '7', '8', 'B'),
            ('2 ta olma va yana 3 ta olma bor. Jami nechta olma?', '4', '5', '6', '7', 'B'),
            ('7 ta konfetdan 2 tasini yeding. Nechta qoldi?', '4', '5', '6', '7', 'B'),
            ('4 + 1 = ?', '4', '5', '6', '7', 'B'),
            ('6 + 3 = ?', '8', '9', '10', '11', 'B'),
            ('5 - 5 = ?', '0', '1', '2', '5', 'A'),
            ('0 + 7 = ?', '0', '5', '6', '7', 'D')],
 '1-sinf': [('Qaysi son faqat 5 larni qo‘shish orqali hosil bo‘lmaydi?', '15', '20', '24', '30', 'C'),
            ('Ketma-ketlikdagi keyingi sonni toping: 4, 9, 15, 22, ___', '28', '29', '30', '31', 'B'),
            ('Qaysi sonlar yig‘indisi 65 ga teng emas?', '30 va 35', '25 va 40', '32 va 33', '28 va 38', 'D'),
            ('Qaysi ifoda eng katta natijani beradi?', '45 + 18', '60 – 12', '33 + 27', '80 – 25', 'A'),
            ('Bir tup daraxtda 76 ta olma bor. 28 tasi yerga tushdi. Daraxtda nechta olma qoldi?',
             '47',
             '48',
             '49',
             '50',
             'B'),
            ('Noma’lum sonni toping: x – 23 = 15', '36', '37', '38', '39', 'C'),
            ('Noma’lum sonni toping: x + 24 = 56', '30', '31', '32', '33', 'C'),
            ('2 soat 20 minut jami necha minut?', '120', '130', '140', '150', 'C'),
            ('Qaysi qatorda sonlar kamayish tartibida joylashgan?',
             '45, 50, 55, 60',
             '80, 75, 70, 65',
             '32, 34, 36, 38',
             '25, 30, 28, 35',
             'B'),
            ('70 sonini 4 marta 6 tadan kamaytiring. Natija nechaga teng?', '42', '44', '46', '48', 'C'),
            ('Bir daftar 9 so‘m turadi. 7 ta daftar qancha turadi?', '56', '63', '64', '72', 'B'),
            ('Qaysi son 90 dan 7 ga kichik?', '81', '82', '83', '84', 'C'),
            ('Ketma-ketlikdagi keyingi sonni toping: 2, 5, 10, 17, ___', '24', '25', '26', '27', 'C'),
            ('Qaysi son 5 o‘nlik va 9 birlikdan iborat?', '59', '95', '50', '59', 'A'),
            ('4 ta uchburchakda jami nechta tomon bor?', '8', '10', '12', '14', 'C'),
            ('Bir qutida 80 ta qalam bor. 5 marta 7 tadan berildi. Nechta qalam qoldi?', '40', '42', '44', '45', 'D'),
            ('Bir bola 8 kunda jami 56 bet kitob o‘qidi. Har kuni teng o‘qigan bo‘lsa, bir kunda nechta bet o‘qigan?',
             '6',
             '7',
             '8',
             '9',
             'B'),
            ('36 ga nechani qo‘shsak 54 bo‘ladi?', '16', '17', '18', '19', 'C'),
            ('Soat 2:15 dan 3:05 gacha necha minut vaqt o‘tadi?', '45', '48', '50', '52', 'C'),
            ('1 hafta va yana 4 kun necha kun bo‘ladi?', '9', '10', '11', '12', 'C')],
 '2-sinf': [('Seyf 5, 2 va 7 raqamlaridan tuzilgan kod yordamida ochiladi. Seyfning kodi 500 dan katta bo‘lgan toq son '
             'bo‘lib, beshga karralidir. Bu qaysi son bo‘ladi?',
             '527',
             '275',
             '725',
             '257',
             'C'),
            ('Har bir keyingi raqami oldingisidan bittaga ortiq bo‘lgan nechta uch xonali son yozish mumkin?',
             '7 ta',
             '8 ta',
             '9 ta',
             '10 ta',
             'A'),
            ('Buvi 56 yoshda, nevarasi 14 yoshda. Buvi necha yildan keyin nevarasidan 2 marta katta bo‘ladi?',
             '22',
             '28',
             '14',
             '12',
             'B'),
            ('Arqon 6 joyidan qirqilgan bo‘lsa, nechta bo‘lak hosil bo‘ladi?', '6 ta', '5 ta', '12 ta', '7 ta', 'D'),
            ('Kiyim tikuvchida 24 m li gazlama bo‘lib, u har kuni 3 m gazlamani qirqib olib kiyim tikadi. Necha kundan '
             'so‘ng u oxirgi bo‘lakni kesib oladi?',
             '7',
             '8',
             '6',
             '5',
             'A'),
            ('9 ta qog‘oz varag‘i bor edi. Ulardan bir nechtasi 3 qismga qirqilgandan so‘ng, varaqlar soni 15 ta '
             'bo‘ldi. Nechta qog‘oz varag‘i qirqilgan?',
             '4 ta',
             '3 ta',
             '2 ta',
             '5 ta',
             'B'),
            ('Uchta javonda 376 ta kitob bor. Birinchi va ikkinchi javonda 186 ta, ikkinchi va uchinchi javonda esa '
             '277 ta kitob bor. Ikkinchi javonda nechta kitob bor?',
             '87',
             '67',
             '190',
             '99',
             'A'),
            ('2 ta oshpaz sabzi to‘g‘rashmoqda. Ulardan biri 1 minutda 2 ta, ikkinchisi esa 3 ta sabzini to‘g‘rab, '
             'ikkalasi birgalikda 450 dona sabzini to‘g‘radi. Shunda ikkinchi oshpaz nechta sabzini to‘g‘ragan?',
             '180 ta',
             '150 ta',
             '225 ta',
             '270 ta',
             'D'),
            ('4 kg mayiz olish uchun 20 kg uzumni quritish kerak. 3 kg mayiz olish uchun necha kg uzumni quritish '
             'kerak?',
             '16 kg',
             '15 kg',
             '17 kg',
             '3 kg',
             'B'),
            ('Quyidagi sonlardan qaysi biri 14 ga bo‘linmaydi?', '56', '156', '196', '140', 'B'),
            ('Kvadratning perimetri 40 sm ga teng. Uning tomoni necha dm?', '2 dm', '3 dm', '1 dm', '4 dm', 'C'),
            ('Bo‘chkada to‘la bo‘yoq bor. Anvar uni 3 kg li idishlardan 36 tasiga quygandan so‘ng bo‘chkaning teng '
             'yarmi bo‘shadi. Bo‘chkada dastlab qancha bo‘yoq bo‘lgan?',
             '216 kg',
             '108 kg',
             '39 kg',
             '54 kg',
             'A'),
            ('Bug‘doy dalasi to‘g‘ri to‘rtburchak shaklida bo‘lib, eni 300 m, bo‘yi esa enidan 93 m ko‘p. Uning '
             'perimetrini toping.',
             '1386 sm',
             '1386 m',
             '693 m',
             '1286 m',
             'B'),
            ('Omborda 930 kg sabzavot va 170 kg meva bor. Barcha mahsulotning to‘rtdan bir qismini bolalar uyiga '
             'jo‘natildi. Ombordan necha kg mahsulot jo‘natilgan?',
             '33 kg',
             '275 kg',
             '255 kg',
             '1100 kg',
             'B'),
            ('Poyezd 360 km yo‘lni 6 soatda bosib o‘tishi uchun qancha tezlik bilan yurishi kerak?',
             '360 km/soat',
             '60 km/soat',
             '21 km/soat',
             '2160 km/soat',
             'B'),
            ('Ayiqcha o‘yinchoq 56 so‘m turadi. 560112 so‘mga nechta ayiqcha olish mumkin?',
             '12 ta',
             '10002 ta',
             '1002 ta',
             '1000 ta',
             'B'),
            ('Zuhro 4-sinfda o‘qiydi, kasalligi tufayli maktabga 8 hafta bormadi. U necha kun maktabga bormagan?',
             '56 kun',
             '48 kun',
             '64 kun',
             '40 kun',
             'D'),
            ('Qaysi sonni 3 ga bo‘lsak 110 chiqadi?', '44', '999', '330', '3030', 'C'),
            ('Tenglamani yeching. (80 - 20 : 5) = 19', '2', '3', '0', '1', 'D'),
            ('Uch xonali sonlar nechta?', '900 ta', '899 ta', '910 ta', '889 ta', 'A')],

 '3-sinf': [
            ('Rasmda jami nechta butun olma bor.', '6', '7', '8', '6', 'B', '/question-images/matematika_visual_q01.png'),
            ('Sinfdagi to‘rt o‘quvchining bo‘ylari berilgan. Eng uzun va eng qisqa bo‘y orasidagi farqni millimetrda toping.', '67', '670', '61', '458', 'B', '/question-images/matematika_visual_q02.png'),
            ('Berilgan ma’lumotlardan ? o‘rnidagi sonni toping.', '110', '160', '150', '170', 'C', '/question-images/matematika_visual_q03.png'),
            ('Sanjar uchta otdi va ikki marta aniq bir xil joyga, bir marta ko‘k rangli joyga tegdi. Jami ballni toping.', '29', '28', '27', '26', 'B', '/question-images/matematika_visual_q04.png'),
            ('8 ta sigir, 5 ta tovuq, 3 ta ilon bor. Hayvonlarning jami nechta oyog‘i bo‘ladi? Ilonda 1 ta oyoq deb hisoblang.', '44', '42', '46', '45', 'D'),
            ('12 ta rasm va 3 ta video jami qancha hajm egallashini toping.', '69', '70', '68', '71', 'A'),
            ('Do – Ri – Mi – FA ketma-ketligida 39-o‘rinda qaysi tovush keladi?', 'Do', 'FA', 'Ri', 'Mi', 'D'),
            ('Mikki 0,6,1,3 raqamlaridan eng kichik uch xonali son hosil qildi. Shu sondan eng katta raqamni ayirish natijasida javob nechchi chiqadi?', '106', '103', '98', '94', 'D', '/question-images/matematika_visual_q08.png'),
            ('Qopda 20 ta qora, 15 ta ko‘k, 12 ta qizil shar bor. Kamida nechta shar olinsa, aniq bitta ko‘k shar olinadi?', '20', '15', '32', '33', 'D'),
            ('Kubning qirrasi 3 cm bo‘lsa, uning barcha qirralari yig‘indisi necha cm bo‘ladi?', '36', '38', '18', '34', 'A'),
            ('2 ta galstuk, 2 ta ko‘ylak va 3 xil shimdan nechta usulda kiyinish mumkin?', '5', '4', '6', '12', 'D', '/question-images/matematika_visual_q11.png'),
            ('1 ta kran bo‘sh hovuzni 12 soatda to‘ldirsa, 4 ta kran 2 ta shunday hovuzni necha soatda to‘ldiradi?', '24', '12', '6', '96', 'C', '/question-images/matematika_visual_q12.png'),
            ('Pingvin 60 m/minut tezlikda 16 soat yursa, tog‘gacha masofa necha metr?', '57700', '57600', '58700', '59000', 'B', '/question-images/matematika_visual_q13.png'),
            ('M1 Abrams tanki bir daqiqada 6 ta o‘q ota oladi. 5 daqiqada jami nechta snaryad otadi?', '11', '30', '1', '40', 'B', '/question-images/matematika_visual_q14.png'),
            ('Qorqiz, Rapunzel va Zolushka toj ranglari shartlari bo‘yicha Zolushka qanday toj kiygan?', 'ko‘k', 'yashil', 'qizil', 'oq', 'C', '/question-images/matematika_visual_q15.png'),
            ('Uchburchak bir tomoni 15 sm, ikkinchi tomoni undan 2 sm kalta, uchinchi tomon ikki tomon o‘rta arifmetigiga teng. Perimetrni toping.', '42', '50', '54', '48', 'A'),
            ('Tenglamani yeching va javobiga 6 ni qo‘shing: (A · 6 + 12) · 3 = 72', '8', '10', '12', '2', 'A'),
            ('Katakli doskadagi nechta sonni 8 ga bo‘lganda 1 qoldiq qoladi?', '0 ta', '1 ta', '2 ta', '3 ta', 'C', '/question-images/matematika_visual_q18.png'),
            ('Grafikka ko‘ra 2010–2014-yillarda jami nechta avtomobil sotilgan?', '23', '34', '25', '24', 'C', '/question-images/matematika_visual_q19.png'),
            ('Qonuniyatni aniqlab, ? o‘rnida qanday son yashiringanini toping: 52, 46, ?, 34', '39', '42', '41', '40', 'D')],

 '4-sinf': [
            ('Rasmda jami nechta butun olma bor.', '6', '7', '8', '6', 'B', '/question-images/matematika_visual_q01.png'),
            ('Sinfdagi to‘rt o‘quvchining bo‘ylari berilgan. Eng uzun va eng qisqa bo‘y orasidagi farqni millimetrda toping.', '67', '670', '61', '458', 'B', '/question-images/matematika_visual_q02.png'),
            ('Berilgan ma’lumotlardan ? o‘rnidagi sonni toping.', '110', '160', '150', '170', 'C', '/question-images/matematika_visual_q03.png'),
            ('Sanjar uchta otdi va ikki marta aniq bir xil joyga, bir marta ko‘k rangli joyga tegdi. Jami ballni toping.', '29', '28', '27', '26', 'B', '/question-images/matematika_visual_q04.png'),
            ('8 ta sigir, 5 ta tovuq, 3 ta ilon bor. Hayvonlarning jami nechta oyog‘i bo‘ladi? Ilonda 1 ta oyoq deb hisoblang.', '44', '42', '46', '45', 'D'),
            ('12 ta rasm va 3 ta video jami qancha hajm egallashini toping.', '69', '70', '68', '71', 'A'),
            ('Do – Ri – Mi – FA ketma-ketligida 39-o‘rinda qaysi tovush keladi?', 'Do', 'FA', 'Ri', 'Mi', 'D'),
            ('Mikki 0,6,1,3 raqamlaridan eng kichik uch xonali son hosil qildi. Shu sondan eng katta raqamni ayirish natijasida javob nechchi chiqadi?', '106', '103', '98', '94', 'D', '/question-images/matematika_visual_q08.png'),
            ('Qopda 20 ta qora, 15 ta ko‘k, 12 ta qizil shar bor. Kamida nechta shar olinsa, aniq bitta ko‘k shar olinadi?', '20', '15', '32', '33', 'D'),
            ('Kubning qirrasi 3 cm bo‘lsa, uning barcha qirralari yig‘indisi necha cm bo‘ladi?', '36', '38', '18', '34', 'A'),
            ('2 ta galstuk, 2 ta ko‘ylak va 3 xil shimdan nechta usulda kiyinish mumkin?', '5', '4', '6', '12', 'D', '/question-images/matematika_visual_q11.png'),
            ('1 ta kran bo‘sh hovuzni 12 soatda to‘ldirsa, 4 ta kran 2 ta shunday hovuzni necha soatda to‘ldiradi?', '24', '12', '6', '96', 'C', '/question-images/matematika_visual_q12.png'),
            ('Pingvin 60 m/minut tezlikda 16 soat yursa, tog‘gacha masofa necha metr?', '57700', '57600', '58700', '59000', 'B', '/question-images/matematika_visual_q13.png'),
            ('M1 Abrams tanki bir daqiqada 6 ta o‘q ota oladi. 5 daqiqada jami nechta snaryad otadi?', '11', '30', '1', '40', 'B', '/question-images/matematika_visual_q14.png'),
            ('Qorqiz, Rapunzel va Zolushka toj ranglari shartlari bo‘yicha Zolushka qanday toj kiygan?', 'ko‘k', 'yashil', 'qizil', 'oq', 'C', '/question-images/matematika_visual_q15.png'),
            ('Uchburchak bir tomoni 15 sm, ikkinchi tomoni undan 2 sm kalta, uchinchi tomon ikki tomon o‘rta arifmetigiga teng. Perimetrni toping.', '42', '50', '54', '48', 'A'),
            ('Tenglamani yeching va javobiga 6 ni qo‘shing: (A · 6 + 12) · 3 = 72', '8', '10', '12', '2', 'A'),
            ('Katakli doskadagi nechta sonni 8 ga bo‘lganda 1 qoldiq qoladi?', '0 ta', '1 ta', '2 ta', '3 ta', 'C', '/question-images/matematika_visual_q18.png'),
            ('Grafikka ko‘ra 2010–2014-yillarda jami nechta avtomobil sotilgan?', '23', '34', '25', '24', 'C', '/question-images/matematika_visual_q19.png'),
            ('Qonuniyatni aniqlab, ? o‘rnida qanday son yashiringanini toping: 52, 46, ?, 34', '39', '42', '41', '40', 'D')],

 '6-sinf': [('Hisoblang: 3/7 + 4/9 + 1/2 + 4/7 + 5/9', '2 1/2', '3 1/4', '3 1/7', '2 1/4', 'A'),
            ('Madina 2 ta qalam sotib olish uchun do‘konchiga p so‘m pul berdi. Do‘konchi unga 2000 so‘m qaytim berdi. Bitta qalamning narxini toping.',
             'p - 2000',
             'p · 2000',
             '(p - 2000) / 2',
             '(p - 2000) · 2',
             'C'),
            ('Ifodani soddalashtiring: 2d - 16 + 3f - (d + 3f - 16)', 'd - 32', 'd', 'd + 6f', 'd - 16', 'B'),
            ('Agar z = 7 bo‘lsa, (z² - 1) · 2 algebraik ifodaning qiymati 7 dan qancha ko‘p?', '19', '86', '89', '33', 'C'),
            ('Hisoblang: 1/2 · 3/4 + 1/2 : 9/4', '5/17', '12/72', '91/42', '43/72', 'D'),
            ('100 ming so‘m pul Ali, Ahror va Kamolga bo‘lib berildi. Ahror Alidan ikki barobar ko‘p pul oldi. Kamol Ahrordan 10 ming so‘m kam pul oldi. Kamol qancha pul olgan?',
             '44000 so‘m',
             '34000 so‘m',
             '22000 so‘m',
             '42000 so‘m',
             'B'),
            ('Anvar bozordan jami 200 dona bodring va pomidor ko‘chatlari sotib oldi. Bodring ko‘chatlarining sonini pomidor ko‘chatlari soniga nisbati 13:12 bo‘lsa, bodring ko‘chatlari pomidor ko‘chatlaridan qancha ko‘p?',
             '1 ta',
             '25 ta',
             '8 ta',
             '175 ta',
             'C'),
            ('Shoirbek pulining 2/5 qismiga poyabzal sotib oldi. Unda 30 ming so‘m pul qolgan bo‘lsa, Shoirbekda oldin qancha pul bo‘lgan?',
             '50000 so‘m',
             '30000 so‘m',
             '75000 so‘m',
             '40000 so‘m',
             'A'),
            ('Kasrni qisqarmas shaklda yozing: 48/180', '20/33', '2/3', '1/15', '4/15', 'D'),
            ('Tomoni 1 2/3 cm bo‘lgan kvadratning yuzini toping.', '2,56', '1 4/9', '2 7/9', '25/3', 'C'),
            ('Kuboidning qirralari 3 dm, 4 dm va 10 cm bo‘lsa, uning hajmini toping.', '120', '12', '1,2', '0,12', 'B'),
            ('Katerning oqim bo‘ylab tezligi 35 km/h, oqimga qarshi tezligi 25 km/h ga teng bo‘lsa, oqim tezligini toping.', '10 km/h', '3 km/h', '5 km/h', '60 km/h', 'C'),
            ('x burchak necha gradusga teng?', '57', '123', '55', '68', 'A', '/question-images/matematika_6_sinf_q13.png'),
            ('Berilgan chorak doiraning yuzini toping. Rasmda radius 14 cm. (π ≈ 22/7)', '196 cm²', '154 cm²', '44 cm²', '84 cm²', 'B', '/question-images/matematika_6_sinf_q14.png'),
            ('Soat 12:10 da soat va minut millari orasidagi burchak necha gradusga teng bo‘ladi?', '30', '60', '45', '55', 'D', '/question-images/matematika_6_sinf_q15.png'),
            ('Buyumning narxi 500000 so‘m edi. Keyinchalik u 40% ga arzonlashdi. Endi buyumning narxini aniqlang.', '300000 so‘m', '200000 so‘m', '400000 so‘m', '150000 so‘m', 'A'),
            ('Diagrammada o‘quvchilar fevral oyida, yanvar oyidagidan necha foiz ko‘p kitob o‘qishgan?', '30', '37,5', '35', '40', 'B', '/question-images/matematika_6_sinf_q17.png'),
            ('Radiusi 10 sm bo‘lgan aylananing uzunligini toping.', '31,4 sm', '62,8 sm', '100,8 sm', '131,8 sm', 'B'),
            ('Proporsiyaning noma’lum hadini toping: 48:3 = x : 5', '75', '80', '16', '45', 'B'),
            ('Avtomobil 60 km/h tezlik bilan 3 soat, 65 km/h tezlik bilan 2 soat yo‘l yurdi. Avtomobilning butun yo‘l davomida o‘rtacha tezligini toping?',
             '62 km/h',
             '62,5 km/h',
             '60 km/h',
             '65 km/h',
             'A')],

 '8-sinf': [('Hisoblang: ((4/7) + (4/8) + (4/9)) / ((2/21) + (2/24) + (2/27))', '6', '8', '9', '10', 'A'),
            ('Quyidagilardan qaysi biri 1 ga yaqin?', '8/9', '9/16', '10/11', '11/10', 'D'),
            ('x ning nechta natural qiymatida ushbu 15 / (2x - 3) ifoda noto‘g‘ri kasr bo‘ladi?', '4', '6', '8', '9', 'C'),
            ('Biror x son uchun x + 3/8 ifoda butun son bo‘lsa, x sonining kasr qismini toping.', '0,875', '0,625', '0,375', '0,125', 'B'),
            ('Quyidagi rasmda A va B qutilardagi tuxumlar soni ko‘rsatilgan, ularning ikkalasi ham 10 ta tuxumni sig‘dira oladi. B qutini to‘liq to‘ldirish uchun A qutidagi tuxumlarning qancha qismini B qutiga qo‘shish kerak?', '1/2', '2/3', '3/4', '4/5', 'C', '/question-images/matematika_8_sinf_q05.png'),
            ('Hisoblang: ((4!)² - (3!)²) / (4! + 3!)', '18', '12', '20', '16', 'A'),
            ('(a!)! ≤ 720 shartni qanoatlantiradigan a ning nechta qiymati bor?', '6', '5', '3', '4', 'D'),
            ('0! + 2! + 4! + 6! + ... + 98! sonini 6 ga bo‘lgandagi qoldiqni toping.', '0', '4', '1', '3', 'D'),
            ('XY ikki xonali son. Rasmga ko‘ra XY sonidan nechta yozish mumkin?', '5', '4', '3', '6', 'A', '/question-images/matematika_8_sinf_q09.png'),
            ('Har birining balandligi 18 sm bo‘lgan yetita qutining beshtasi stolga, ikkitasi stol ostidagi polga rasmdagi kabi joylashtirilgan. Bunga ko‘ra ba necha sm bo‘ladi?', '47', '39', '69', '29', 'B', '/question-images/matematika_8_sinf_q10.png'),
            ('Yig‘indini hisoblang: 1 - 2 + 3 - 4 + ... - 124 + 125', '−62', '−63', '63', '62', 'C'),
            ('Hisoblang: (1 + 3 + 5 + ... + 43) / (2 + 4 + 6 + ... + 42)', '22/17', '41/43', '43/42', '22/21', 'D'),
            ('A, B va C musbat butun sonlar. Yuqoridagi bo‘linish amallariga ko‘ra, A ni 21 ga bo‘lgandagi qoldiqni toping.', '1', '4', '5', '7', 'A', '/question-images/matematika_8_sinf_q13.png'),
            ('Agar x = 2^4 · 3^3 · 5^4 va y = 2^3 · 3^4 bo‘lsa, EKUK(x; y) / EKUB(x; y) ni toping.', '4 · 5^4', '3 · 5^4', '6 · 5^4', '3 · 5^6', 'C'),
            ('1-rasmdagi tarozining pallalariga uchburchak va kvadratlardan qo‘yilib 2-rasm hosil qilindi. Uchburchak = (3x + 1) kg va kvadrat = (x + 5) kg. Bunga ko‘ra x necha xil natural son qiymatlarni qabul qilishi mumkin?', '3', '4', '5', '6', 'B', '/question-images/matematika_8_sinf_q15.png'),
            ('Tenglamani yeching: (x² − 4)(2x² − x − 1) = 0', '{−2; −1/2; 1; 2}', '{1; 2; 3; 4}', '{−3; −2/3; 1}', '{−2; 2; 5/2}', 'A'),
            ('Agar ushbu (1 − x + x²)^10 = a₀ + a₁x + a₂x² + ... + a₂₀x²⁰ tenglik o‘rinli bo‘lsa, a₀ + a₂ + ... + a₂₀ ni toping.', '2^10 + 1', '3^10 − 1', '4^10 − 1', '(3^10 + 1) / 2', 'D'),
            ('Agar ushbu ax^4 + bx^3 + cx^2 + dx + e = (x^2 − 1)(px^2 + qx + r) + 2x − 1 tenglik o‘rinli bo‘lsa, a + c + e ni toping.', '−2', '−1', '0', '1', 'B'),
            ('a va b musbat butun sonlar bo‘lib, P(x) = (x + a)(x + b) ko‘phadning koeffitsientlari yig‘indisi 15 bo‘lsa, a · b ni toping.', '10', '9', '8', '7', 'C'),
            ('Yuqoridagi rasmda 60 pog‘onali, doimiy va bir-biriga teng ikkita eskalator ko‘rsatilgan. Ahmet zinapoyaning pastidan tepaga 36 pog‘ona ko‘tarildi, shu vaqtda Selim zinapoyaning tepasidan 42 pog‘ona pastga tushdi. Ahmet tezligining Selim tezligiga nisbati qanday?', '14/9', '7/6', '6/7', '9/14', 'C', '/question-images/matematika_8_sinf_q20.png')],

 '10-sinf': [('Quyida keltirilgan tengliklardan qaysilari ayniyat emas?', '1; 2; 4', '1; 3; 4', '1; 2; 5', '2; 3; 5', 'C'),
            ('3,104·10^-3 + 1,81·10^-2 yig‘indi quyidagi sonlarning qaysi biriga teng?', '2,1204·10^-2', '4,914·10^-5', '3,285·10^-3', '4,914·10^-3', 'A'),
            ('m ning √(m−1), √(5m−1), √(12m+1) lar ko‘rsatilgan tartibda arifmetik progressiya tashkil qiladigan qiymatlarining yig‘indisini toping.', '8', 'm ning bunday qiymatlari yo‘q', '12', '15', 'C'),
            ('(3b + 2) / (x − 1,5) = 2b tenglama b ning qanday qiymatlarida manfiy yechimga ega bo‘ladi?', '(-∞; 0)', '(-∞; -1/3) ∪ (-1/3; 0)', '(-∞; -1/3)', '(-1/3; 0)', 'D'),
            ('y = 1 ga nisbatan y = 2x + 1 ga simmetrik bo‘lgan to‘g‘ri chiziqning tenglamasini toping.', 'y = 1 − 2x', 'y = −2x', 'y = 2x − 1', 'y = 2x', 'A'),
            ('Agar (x − 5)(x/5 + 4) = 0 bo‘lsa, x/5 + 4 qanday qiymatlar qabul qiladi?', '0 yoki 5', '−20 yoki 0', '0 yoki 8', 'faqat 0', 'A'),
            ('Agar log_(b/a)(a^2/b) = −3 bo‘lsa, log_(a^2)(ab) ni hisoblang.', '1', '0,8', '0,10', '0,6', 'D'),
            ('(√32 + √98 − √50) / √72 · √8 ni hisoblang.', '√2', '0,998207', '2', '2√2', 'D'),
            ('Bir jamoadagi insonlarning har biri boshqalardan bittadan kitobni sovg‘a sifatida olyapti. Agar hammasi bo‘lib 600 ta kitob sovg‘a qilingan bo‘lsa, jamoada nechta kishi bo‘lgan?', '23', '24', '25', '26', 'C'),
            ('Bir miqdor qalamning har donasi 1000 so‘mdan sotilsa 6000 so‘m zarar, 1500 so‘mdan sotilsa 9000 so‘m foyda qilinadi. Dastlab nechta qalam bo‘lgan?', '30', '32', '36', '42', 'A'),
            ('Agar a + ((a−3)/a) / ((3/a) − 1) : (3/a) = 4 bo‘lsa, a ni toping.', '1', '2', '4', '6', 'D'),
            ('Biznesmen molining 1/3 qismini 20% foyda bilan, 1/6 qismini 30% foyda bilan va qolgan qismini 40% zarar bilan sotdi. Biznesmen necha % zarar qilganini aniqlang.', '7,5', '25/3', '12,5', '15', 'B'),
            ('Otaning yoshi 4 yil oldin ikki bolasining yoshlari yig‘indisidan 8 marta ko‘p, 24 yildan keyin teng bo‘lsa, otaning hozirgi yoshini toping.', '24', '32', '36', '42', 'C'),
            ('Turist toqqa ko‘tarilayotib, birinchi soatda 800 m balandlikka chiqdi, keyingi har bir soatda esa oldingisiga qaraganda 25 m kam balandlikka ko‘tarildi. U 5700 m balandlikka necha soatda chiqadi?', '9', '7', '1', '8', 'D'),
            ('Agar (2m−n)/(m+2n) = 3 va n < 0 bo‘lsa, quyidagilardan qaysi biri to‘g‘ri?', 'm + n < 0', 'mn > 0', 'm < n', 'm − n > 0', 'D'),
            ('Agar bo‘luvchi x−2 ga, bo‘linma x−1 ga, qoldiq 4 ga teng bo‘lsa, bo‘linuvchi nimaga teng?', 'x^2 + x − 1', 'x^2 − 6', 'x^2 − 3x + 6', 'x^2 − 5', 'C'),
            ('Agar a/b = c/d = e/f = k^2 bo‘lsa, (a·c·f)/(b·d·e) ni toping.', 'k^2', 'k', '1/k^2', '1/k', 'A'),
            ('Agar a = 1/(1/7 + 1/3) va b = 1/(1/3 − 1/13) bo‘lsa, (a − b)^2 ni qiymatini toping.', '1,96', '2,25', '2,56', '3,24', 'D'),
            ('a va b ratsional sonlar uchun a√12 + b√3 − √27 = 3a + b − 6 tenglik o‘rinli bo‘lsa, ab ni qiymatini toping.', '−18', '−9', '−6', '6', 'B'),
            ('Quyidagi ifodalardan qaysi biri ushbu 16x^2 − 4x + y − y^2 ko‘phadga bo‘linadi?', '4x + y + 2', '4x − y + 2', '4x − y − 1', '4x + y − 1', 'D')],

 '11-sinf': [('Berilgan tenglamani qanoatlantiruvchi musbat sonni toping.', 'A variant', 'B variant', 'C variant', 'D variant', 'D'),
            ('Agar berilgan shartlar bajarilsa, noma’lum ifodaning qiymatini toping.', 'A variant', 'B variant', 'C variant', 'D variant', 'C'),
            ('Agar berilgan bo‘lsa, burchakka mos keluvchi nuqta qaysi chorakda joylashgan?', 'I chorak', 'II chorak', 'III chorak', 'IV chorak', 'C'),
            ('m ning qanday qiymatida berilgan hadlar arifmetik progressiyaning ketma-ket hadlari bo‘ladi?', 'A variant', 'B variant', 'C variant', 'D variant', 'C'),
            ('Ushbu tenglamalar sistemasiga ko‘ra noma’lumni toping.', 'A variant', 'B variant', 'C variant', 'D variant', 'C'),
            ('Berilgan funksiyaning qiymatlar sohasini toping.', 'A variant', 'B variant', 'C variant', 'D variant', 'D'),
            ('Quyidagi tenglamani yeching.', 'A variant', 'B variant', 'C variant', 'D variant', 'C'),
            ('Avtomobil haydovchisi birinchi soatda yo‘lning yarmini, ikkinchi soatda qolgan yo‘lning ma’lum qismini, uchinchi soatda esa qolgan  km masofani bosib o‘tdi. U uch soatda jami qancha yo‘l bosib o‘tgan?', 'A variant', 'B variant', 'C variant', 'D variant', 'A'),
            ('Diagonallarining soni tomonlari sonidan ma’lum marta ko‘p bo‘lgan qavariq muntazam ko‘pburchakning tashqi burchaklaridan birini toping.', 'A variant', 'B variant', 'C variant', 'D variant', 'B'),
            ('Hech qaysi uchtasi bir to‘g‘ri chiziqda yotmaydigan nuqtalarni tutashtirish orqali nechta turli kesma hosil qilish mumkin?', 'A variant', 'B variant', 'C variant', 'D variant', 'B'),
            ('Hisoblang.', 'A variant', 'B variant', 'C variant', 'D variant', 'D'),
            ('Berilgan funksiyaning kesmadagi eng kichik qiymatini toping.', 'A variant', 'B variant', 'C variant', 'D variant', 'B'),
            ('Aniq integralni hisoblang.', 'A variant', 'B variant', 'C variant', 'D variant', 'B'),
            ('Berilgan tengsizlikni qanoatlantiruvchi barcha butun sonlar ko‘paytmasini toping.', 'A variant', 'B variant', 'C variant', 'D variant', 'D'),
            ('Berilgan tenglama haqiqiy ildizlari yig‘indisini toping.', 'A variant', 'B variant', 'C variant', 'D variant', 'A'),
            ('Agar ma’lum son tenglamaning ildizi bo‘lsa, boshqa son nechaga teng?', 'A variant', 'B variant', 'C variant', 'D variant', 'A'),
            ('Berilgan funksiya uchun boshlang‘ich funksiyani toping.', 'A variant', 'B variant', 'C variant', 'D variant', 'B'),
            ('Ifodani hisoblang.', 'A variant', 'B variant', 'C variant', 'D variant', 'B'),
            ('Ko‘phadni bir ifodaga bo‘lgandagi qoldiq ma’lum bo‘lsa, boshqa bo‘linishdagi qoldiqni toping.', 'A variant', 'B variant', 'C variant', 'D variant', 'C'),
            ('Berilgan tengsizlikni yeching.', 'A variant', 'B variant', 'C variant', 'D variant', 'C')]
}

class Command(BaseCommand):
    help = "Demo adminni yaratadi, eski testlarni tozalaydi, Mental arifmetika, Ingliz tili 0-7-sinf va Qiyin, Rus tili boxcha, 2-3-4-5-6-7-8-9-10-sinf va Matematika 0-1-2-3-4-6-8-10-11-sinf testlarini qo‘shadi."

    def handle(self, *args, **options):
        with transaction.atomic():
            User.objects.filter(username='admin').delete()
            admin_user, _ = User.objects.get_or_create(
                username='ulugbek',
                defaults={
                    'email': 'ulugbek@example.com',
                    'is_staff': True,
                    'is_superuser': True,
                    'is_active': True,
                }
            )
            admin_user.email = admin_user.email or 'ulugbek@example.com'
            admin_user.is_staff = True
            admin_user.is_superuser = True
            admin_user.is_active = True
            admin_user.set_password('codingwithulugbek20030313')
            admin_user.save()

            Center.objects.get_or_create(name='LIDER.Uz Onlayn Olimpiada')

            # Bazani toza holatga keltiramiz: eski o‘quvchilar, natijalar,
            # fanlar, sinflar va A/B/C/D testlar olib tashlanadi.
            StudentAnswer.objects.all().delete()
            MentalTask.objects.all().delete()
            Result.objects.all().delete()
            Student.objects.all().delete()
            Question.objects.all().delete()
            Level.objects.all().delete()
            Subject.objects.all().delete()

            mental_subject = Subject.objects.create(name='Mental arifmetika')
            Level.objects.create(subject=mental_subject, name='5 yosh', duration_minutes=10)
            Level.objects.create(subject=mental_subject, name='6 yosh', duration_minutes=10)
            Level.objects.create(subject=mental_subject, name='8 yosh', duration_minutes=10)
            Level.objects.create(subject=mental_subject, name='9 yosh', duration_minutes=10)

            english_subject = Subject.objects.create(name='Ingliz tili')
            question_count = 0
            for level_name, questions in ENGLISH_TESTS.items():
                level = Level.objects.create(subject=english_subject, name=level_name, duration_minutes=30)
                Question.objects.bulk_create([
                    Question(
                        subject=english_subject,
                        level=level,
                        text=text,
                        option_a=option_a,
                        option_b=option_b,
                        option_c=option_c,
                        option_d=option_d,
                        correct_answer=correct_answer,
                    )
                    for text, option_a, option_b, option_c, option_d, correct_answer in questions
                ])
                question_count += len(questions)

            rus_subject = Subject.objects.create(name='Rus tili')
            rus_count = 0
            for level_name, questions in RUS_TESTS.items():
                level = Level.objects.create(subject=rus_subject, name=level_name, duration_minutes=30)
                Question.objects.bulk_create([
                    Question(
                        subject=rus_subject,
                        level=level,
                        text=item[0],
                        option_a=item[1],
                        option_b=item[2],
                        option_c=item[3],
                        option_d=item[4],
                        correct_answer=item[5],
                    )
                    for item in questions
                ])
                rus_count += len(questions)

            math_subject = Subject.objects.create(name='Matematika')
            math_count = 0
            for level_name, questions in MATH_TESTS.items():
                level = Level.objects.create(subject=math_subject, name=level_name, duration_minutes=30)
                Question.objects.bulk_create([
                    Question(
                        subject=math_subject,
                        level=level,
                        text=item[0],
                        option_a=item[1],
                        option_b=item[2],
                        option_c=item[3],
                        option_d=item[4],
                        correct_answer=item[5],
                        image=item[6] if len(item) > 6 else '',
                    )
                    for item in questions
                ])
                math_count += len(questions)

        self.stdout.write(self.style.SUCCESS('Admin login tayyor: ulugbek / codingwithulugbek20030313'))
        self.stdout.write(self.style.SUCCESS('Fanlar tayyor: Mental arifmetika (5 yosh, 6 yosh, 8 yosh, 9 yosh), Ingliz tili, Rus tili, Matematika.'))
        self.stdout.write(self.style.SUCCESS(f'Ingliz tili testlari qo‘shildi: {question_count} ta savol.'))
        self.stdout.write(self.style.SUCCESS(f'Rus tili testlari qo‘shildi: {rus_count} ta savol.'))
        self.stdout.write(self.style.SUCCESS(f'Matematika testlari qo‘shildi: {math_count} ta savol.'))
