[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "gcc", "postgresql"]

[phases.install]
cmds = [
  "virtualenv .venv",
  ". .venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  ". .venv/bin/activate && python manage.py collectstatic --noinput"
]

[start]
cmd = ". .venv/bin/activate && bash start.sh"
